#! /usr/bin/perl 

use strict;
use warnings;
use feature 'say';
#use lib qw( ./  /home/toshi/perl/lib );
use DateTimeEasy qw (datestr);
use Pause qw( pause );

my $ltime = localtime;
say $ltime;

my @t = (
					"2013年1月8日 17時33分54秒",
					"2013年1月8日 17時33分頃",
					"2013/1/8 17:34:23",
					"2013/1/8 17:34",
			);


foreach my $var (@t){
	say $var;
	say "format 'HTTP'     "  . datestr($var,'HTTP');
	say "format 'Mail'     "  . datestr($var,'Mail');
	say "format 'SQLite'   "  . datestr($var,'SQLite');
	say "format 'RFC3501'  "  . datestr($var,'RFC3501');
	say "format 'RFC3339'  "  . datestr($var,'RFC3339');
	say "format 'W3CDTF'   "  . datestr($var,'W3CDTF');
	say "format '%c'       "  . datestr($var,'%c');
	say "format '%x'       "  . datestr($var,'%x');
	say "format '%X'       "  . datestr($var,'%X');
	say "format '%Z'       "  . datestr($var,'%Z');
	say "format '%F'       "  . datestr($var,'%F');
	say "standard          "  . datestr($var,'standard');
	say "epoch_sec         "  . datestr($var, 'epoch_sec');
	say "Instans           "  . datestr($var);
	say "----------------------------";
	pause;
}

