#! /usr/bin/perl 

use strict;
use warnings;
use feature 'say';
#use lib qw ( ./ /home/toshi/perl/lib );
use DateTimeEasy qw (datestr);
use Pause qw( pause );

my $ltime = localtime;
say $ltime;

my @t = (
				 "Feb 2 2012 12:10:23",
					$ltime,
					"now",
					"+3:47",
					"-10 business days",
					"next monday",
					"last saturday",
					"-3 days",
					"2012-07-01",
					"2010-6-30",
					"2012年6月28日",
					"2012年07月10日",
					"発信時間： 2012/09/29 11:26:24 | チャイナネット |",
			);


foreach my $var (@t){
	say $var;
	say "format 'HTTP'     "  . datestr($var,'HTTP');
	say "format 'Mail'     "  . datestr($var,'Mail');
	say "format 'SQLite'   "  . datestr($var,'SQLite');
	say "format 'RFC3501'  "  . datestr($var,'RFC3501');
	say "format 'RFC3339'  "  . datestr($var,'RFC3339');
	say "format 'W3CDTF'   "  . datestr($var,'W3CDTF');
	say "format '%c'       "  . datestr($var,'%c');
	say "format '%x'       "  . datestr($var,'%x');
	say "format '%X'       "  . datestr($var,'%X');
	say "format '%Z'       "  . datestr($var,'%Z');
	say "format '%F'       "  . datestr($var,'%F');
	say "standard          "  . datestr($var,'standard');
	say "epoch_sec         "  . datestr($var,'epoch_sec');
	say "Instans           "  . datestr($var);
	say "----------------------------";
	pause;
}

