#! /usr/bin/perl 

use strict;
use warnings;
use utf8;
use feature 'say';

my $time_strings = '発信時間： 2012/09/29 11:26:24 | チャイナネット |'; 

$time_strings =~ s/(\d{4}\D\d{2}\D\d{2}\s\d{2}\D\d{2}\D\d{2})/$1/;

say $1;

my $time_strings2 = $1;


say $time_strings;
say $time_strings2;
