#! /usr/bin/perl 

use strict;
use warnings;
use utf8;
use feature 'say';

my $time_strings = '2012年3月2日';

if ($time_strings =~ /(年|月|日)/ ){
  $time_strings =~ /(\d+)\D+(\d+)\D+(\d+)\D+/;
	$time_strings = sprintf ("%04d-%02d-%02d", $1,$2,$3);
}

say $time_strings;

my $time_strings2 = '2010-6-30';

if ($time_strings2 =~ /^\d+\D+\d+\D+\d+/ ){
  $time_strings2 =~ /(\d+)\D+(\d+)\D+(\d+)/;
	my ($a,$b,$c);
	$a = $b = $c = '%02d';
	$1>100 ? $a = '%04d':
	$2>100 ? $b = '%04d':
	$3>100 ? $c = '%04d':
	undef;

	$time_strings2 = sprintf ("$a-$b-$c", $1,$2,$3);
}

say $time_strings2;
